### ISSUE TITLE
^  SyntaxError: Unexpected token .     at Module._compile (internal/modules/cjs/loader.js:723:23)   

### ISSUE THREAD

**Issue by qkum** [HitomaruKonpaku/twspace-crawler#14]
**Hello there 🌵** 

Firstly, thanks for all your hard work 🧑‍💼 

I suspect you did a typo or commented something out that is the cause of the error.

I'm not a pro at programming yet so I may be wrong though.

I followed the install instructions + installed node with `sudo apt install node ` (The Ubuntu console gave me the command)

Ubuntu 20.04
Python 3.9
node --version: v10.19.0
ffmpeg version 4.4.1-0 ubuntu1~20.04.sav0 Copyright (c) 2000-2021 the FFmpeg developers built with gcc 9 (Ubuntu 9.3.017ubuntu1~20.04)
New anaconda environment
Git clone repo a few hours ago.

**The error:**
Person_1 etc. = left out for the purpose of OPSEC
```
(twspace-crawler) judo@judo-VM:~/twspace-crawler$ node ./dist/index.js --user Person_1,Person_2,Person_3,Person_4
/home/judo/twspace-crawler/dist/utils/PeriscopeUtil.js:18
        return data.match(chunkIndexPattern)?.map((v) => Number(v)) || [];
                                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/judo/twspace-crawler/dist/apis/PeriscopeApi.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
(twspace-crawler) judo@judo-VM:~/twspace-crawler$ node ./dist/index.js --user RichardHeartWin,FundingGym,Hexologist31,HexOrca
/home/judo/twspace-crawler/dist/utils/PeriscopeUtil.js:18
        return data.match(chunkIndexPattern)?map((v) => Number(v)) || [];
                                                                        ^
```

**Comment by qkum** [comment]
I figured out the error now.

It did not install node 14 as you would assume.

But a totally outdated one it seems.

**Comment by qkum** [comment]
Here are the commands you need to install **Node 14:**

```
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt install -y nodejs
```
